model_parameters:
  rfc:
    type: rfc
    n_estimators: 200
    min_samples_split: 3
    min_samples_leaf: 2
    max_features: 3
    max_depth: 17
    bootstrap: True
    class_weight: balanced
    n_jobs: -1

  knn:
    type: knn
    weights: distance
    p: 1
    n_neighbors: 8
    n_jobs: -1

  svm:
    type: svm
    shrinking: True
    probability: True
    kernel: rbf
    gamma: scale
    degree: 2
    coef0: 100
    C: 100
    class_weight: balanced

# K-Fold Cross Validation parameters
kfcv_k: 6
kfcv_scoring: f1_macro